from typing import Protocol
from uuid import UUID


class EmailServiceClientProtocol(Protocol):
    async def create_email(self, *, user_id: UUID, email: str) -> dict: ...

    async def update_email(self, *, user_id: UUID, email: str) -> dict: ...

    async def delete_email(self, *, user_id: UUID) -> None: ...

    async def confirm_email(self, *, code: str) -> dict: ...

    async def send_confirmation(self, *, user_id: UUID) -> dict: ...
