name: Check

on:
  push:
    branches:
      - main
      - release
      - feature/actions-ci
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

      - name: Install deps
        run: uv sync --locked

      - name: mypy
        run: uv run mypy src

      - name: flake8
        run: uv run flake8

      - name: ruff
        run: uv run ruff check src

      - name: test
        run: uv run pytest

