name: Check

on:
  push:
    branches:
      - main
      - release

env:
  IMAGE: ghcr.io/igor-526/eqsitecms-backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

      - name: Install deps
        run: uv sync --locked

      - name: mypy
        run: uv run mypy src

      - name: flake8
        run: uv run flake8

      - name: ruff
        run: uv run ruff check src

      - name: pytest
        run: uv run pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/release'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}

