from .base_repository import TenantBaseRepositoryProtocol
from .breed_repository import BreedRepositoryProtocol
from .coat_color_repository import CoatColorRepositoryProtocol
from .equestrian_repository import EquestrianRepositoryProtocol
from .horse_owner_repository import HorseOwnerRepositoryProtocol
from .horse_repository import HorseChildrenRepositoryProtocol, HorseRepositoryProtocol
from .horse_service_repository import HorseServiceRepositoryProtocol
from .news_repository import NewsRepositoryProtocol
from .photo_repository import PhotoRepositoryProtocol
from .price_repository import PriceGroupRepositoryProtocol, PriceRepositoryProtocol
from .site_settings_repository import SiteSettingsRepositoryProtocol
from .token_repository import TokenRepositoryProtocol
from .user_repository import UserRepositoryProtocol
